#ifndef _ZEPHYR_NUCLEO_WL55JC_RETURN_VALUES_H
#define _ZEPHYR_NUCLEO_WL55JC_RETURN_VALUES_H

enum pulse_pro_return_values
{
    ROUTINE_OK = 0,
    ROUTINE_RETURNING_EARLY_FOR_DEV_PURPOSES,

// Zephyr RTOS device handle related:
    Z__WARNING__NULL_DEVICE_POINTER,
    Z__WARNING__FAIL_ON_DEVICE_GET_BINDING,
    Z__WARNING__FAIL_ON_GPIO_PIN_CONFIGURE,
    Z__WARNING__FAIL_ON_GPIO_PIN_SET,
    Z__INFO__DEVICE_ALREADY_INITIALIZED_OR_NOT_NULL,
};




#endif // _ZEPHYR_NUCLEO_WL55JC_RETURN_VALUES_H
